# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pypudding_w', [dirname(__file__)])
        except ImportError:
            import _pypudding_w
            return _pypudding_w
        if fp is not None:
            try:
                _mod = imp.load_module('_pypudding_w', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pypudding_w = swig_import_helper()
    del swig_import_helper
else:
    import _pypudding_w
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def IP_getJsonResultsObj(uutHandle):
    return _pypudding_w.IP_getJsonResultsObj(uutHandle)
IP_getJsonResultsObj = _pypudding_w.IP_getJsonResultsObj

_pypudding_w.IP_API_VERSION_swigconstant(_pypudding_w)
IP_API_VERSION = _pypudding_w.IP_API_VERSION

_pypudding_w.IP_API_VERSION_MINOR_swigconstant(_pypudding_w)
IP_API_VERSION_MINOR = _pypudding_w.IP_API_VERSION_MINOR

_pypudding_w.IP_FAIL_swigconstant(_pypudding_w)
IP_FAIL = _pypudding_w.IP_FAIL

_pypudding_w.IP_PASS_swigconstant(_pypudding_w)
IP_PASS = _pypudding_w.IP_PASS

_pypudding_w.IP_NA_swigconstant(_pypudding_w)
IP_NA = _pypudding_w.IP_NA

_pypudding_w.IP_SITE_swigconstant(_pypudding_w)
IP_SITE = _pypudding_w.IP_SITE

_pypudding_w.IP_PRODUCT_swigconstant(_pypudding_w)
IP_PRODUCT = _pypudding_w.IP_PRODUCT

_pypudding_w.IP_BUILD_STAGE_swigconstant(_pypudding_w)
IP_BUILD_STAGE = _pypudding_w.IP_BUILD_STAGE

_pypudding_w.IP_BUILD_SUBSTAGE_swigconstant(_pypudding_w)
IP_BUILD_SUBSTAGE = _pypudding_w.IP_BUILD_SUBSTAGE

_pypudding_w.IP_REMOTE_ADDR_swigconstant(_pypudding_w)
IP_REMOTE_ADDR = _pypudding_w.IP_REMOTE_ADDR

_pypudding_w.IP_LOCATION_swigconstant(_pypudding_w)
IP_LOCATION = _pypudding_w.IP_LOCATION

_pypudding_w.IP_LINE_NUMBER_swigconstant(_pypudding_w)
IP_LINE_NUMBER = _pypudding_w.IP_LINE_NUMBER

_pypudding_w.IP_STATION_NUMBER_swigconstant(_pypudding_w)
IP_STATION_NUMBER = _pypudding_w.IP_STATION_NUMBER

_pypudding_w.IP_STATION_TYPE_swigconstant(_pypudding_w)
IP_STATION_TYPE = _pypudding_w.IP_STATION_TYPE

_pypudding_w.IP_SCREEN_COLOR_swigconstant(_pypudding_w)
IP_SCREEN_COLOR = _pypudding_w.IP_SCREEN_COLOR

_pypudding_w.IP_STATION_IP_swigconstant(_pypudding_w)
IP_STATION_IP = _pypudding_w.IP_STATION_IP

_pypudding_w.IP_DCS_IP_swigconstant(_pypudding_w)
IP_DCS_IP = _pypudding_w.IP_DCS_IP

_pypudding_w.IP_PDCA_IP_swigconstant(_pypudding_w)
IP_PDCA_IP = _pypudding_w.IP_PDCA_IP

_pypudding_w.IP_KOMODO_IP_swigconstant(_pypudding_w)
IP_KOMODO_IP = _pypudding_w.IP_KOMODO_IP

_pypudding_w.IP_SPIDERCAB_IP_swigconstant(_pypudding_w)
IP_SPIDERCAB_IP = _pypudding_w.IP_SPIDERCAB_IP

_pypudding_w.IP_FUSING_IP_swigconstant(_pypudding_w)
IP_FUSING_IP = _pypudding_w.IP_FUSING_IP

_pypudding_w.IP_DROPBOX_IP_swigconstant(_pypudding_w)
IP_DROPBOX_IP = _pypudding_w.IP_DROPBOX_IP

_pypudding_w.IP_SFC_IP_swigconstant(_pypudding_w)
IP_SFC_IP = _pypudding_w.IP_SFC_IP

_pypudding_w.IP_SFC_URL_swigconstant(_pypudding_w)
IP_SFC_URL = _pypudding_w.IP_SFC_URL

_pypudding_w.IP_PROV_IP_swigconstant(_pypudding_w)
IP_PROV_IP = _pypudding_w.IP_PROV_IP

_pypudding_w.IP_DATE_TIME_swigconstant(_pypudding_w)
IP_DATE_TIME = _pypudding_w.IP_DATE_TIME

_pypudding_w.IP_STATION_ID_swigconstant(_pypudding_w)
IP_STATION_ID = _pypudding_w.IP_STATION_ID

_pypudding_w.IP_GROUNDHOG_IP_swigconstant(_pypudding_w)
IP_GROUNDHOG_IP = _pypudding_w.IP_GROUNDHOG_IP

_pypudding_w.IP_MAC_swigconstant(_pypudding_w)
IP_MAC = _pypudding_w.IP_MAC

_pypudding_w.IP_SAVE_BRICKS_swigconstant(_pypudding_w)
IP_SAVE_BRICKS = _pypudding_w.IP_SAVE_BRICKS

_pypudding_w.IP_LOCAL_CSV_swigconstant(_pypudding_w)
IP_LOCAL_CSV = _pypudding_w.IP_LOCAL_CSV

_pypudding_w.IP_REALTIME_PARAMETRIC_swigconstant(_pypudding_w)
IP_REALTIME_PARAMETRIC = _pypudding_w.IP_REALTIME_PARAMETRIC

_pypudding_w.IP_SINGLE_CSV_UUT_swigconstant(_pypudding_w)
IP_SINGLE_CSV_UUT = _pypudding_w.IP_SINGLE_CSV_UUT

_pypudding_w.IP_STATION_DISPLAY_NAME_swigconstant(_pypudding_w)
IP_STATION_DISPLAY_NAME = _pypudding_w.IP_STATION_DISPLAY_NAME

_pypudding_w.IP_URI_CONFIG_PATH_swigconstant(_pypudding_w)
IP_URI_CONFIG_PATH = _pypudding_w.IP_URI_CONFIG_PATH

_pypudding_w.IP_SFC_QUERY_UNIT_ON_OFF_swigconstant(_pypudding_w)
IP_SFC_QUERY_UNIT_ON_OFF = _pypudding_w.IP_SFC_QUERY_UNIT_ON_OFF

_pypudding_w.IP_SFC_TIMEOUT_swigconstant(_pypudding_w)
IP_SFC_TIMEOUT = _pypudding_w.IP_SFC_TIMEOUT

_pypudding_w.IP_GHSI_LASTUPDATE_TIMEOUT_swigconstant(_pypudding_w)
IP_GHSI_LASTUPDATE_TIMEOUT = _pypudding_w.IP_GHSI_LASTUPDATE_TIMEOUT

_pypudding_w.IP_FERRET_NOT_RUNNING_TIMEOUT_swigconstant(_pypudding_w)
IP_FERRET_NOT_RUNNING_TIMEOUT = _pypudding_w.IP_FERRET_NOT_RUNNING_TIMEOUT

_pypudding_w.IP_NETWORK_NOT_OK_TIMEOUT_swigconstant(_pypudding_w)
IP_NETWORK_NOT_OK_TIMEOUT = _pypudding_w.IP_NETWORK_NOT_OK_TIMEOUT

_pypudding_w.IP_STATION_SET_CONTROL_BIT_ON_OFF_swigconstant(_pypudding_w)
IP_STATION_SET_CONTROL_BIT_ON_OFF = _pypudding_w.IP_STATION_SET_CONTROL_BIT_ON_OFF

_pypudding_w.IP_CONTROL_BITS_TO_CHECK_ON_OFF_swigconstant(_pypudding_w)
IP_CONTROL_BITS_TO_CHECK_ON_OFF = _pypudding_w.IP_CONTROL_BITS_TO_CHECK_ON_OFF

_pypudding_w.IP_CONTROL_BITS_TO_CLEAR_ON_PASS_ON_OFF_swigconstant(_pypudding_w)
IP_CONTROL_BITS_TO_CLEAR_ON_PASS_ON_OFF = _pypudding_w.IP_CONTROL_BITS_TO_CLEAR_ON_PASS_ON_OFF

_pypudding_w.IP_CONTROL_BITS_TO_CLEAR_ON_FAIL_ON_OFF_swigconstant(_pypudding_w)
IP_CONTROL_BITS_TO_CLEAR_ON_FAIL_ON_OFF = _pypudding_w.IP_CONTROL_BITS_TO_CLEAR_ON_FAIL_ON_OFF

_pypudding_w.IP_ACTIVATION_IP_swigconstant(_pypudding_w)
IP_ACTIVATION_IP = _pypudding_w.IP_ACTIVATION_IP

_pypudding_w.IP_LINE_MANAGER_IP_swigconstant(_pypudding_w)
IP_LINE_MANAGER_IP = _pypudding_w.IP_LINE_MANAGER_IP

_pypudding_w.IP_GDADMIN_swigconstant(_pypudding_w)
IP_GDADMIN = _pypudding_w.IP_GDADMIN

_pypudding_w.IP_RAFT_LINE_swigconstant(_pypudding_w)
IP_RAFT_LINE = _pypudding_w.IP_RAFT_LINE

_pypudding_w.IP_USB_STORAGE_swigconstant(_pypudding_w)
IP_USB_STORAGE = _pypudding_w.IP_USB_STORAGE

_pypudding_w.IP_FIREWALL_swigconstant(_pypudding_w)
IP_FIREWALL = _pypudding_w.IP_FIREWALL

_pypudding_w.IP_UNIT_PROCESS_REQUIRE_BOBCAT_swigconstant(_pypudding_w)
IP_UNIT_PROCESS_REQUIRE_BOBCAT = _pypudding_w.IP_UNIT_PROCESS_REQUIRE_BOBCAT

_pypudding_w.IP_GROUNDHOG_STARTED_swigconstant(_pypudding_w)
IP_GROUNDHOG_STARTED = _pypudding_w.IP_GROUNDHOG_STARTED

_pypudding_w.IP_LAST_RESTORED_swigconstant(_pypudding_w)
IP_LAST_RESTORED = _pypudding_w.IP_LAST_RESTORED

_pypudding_w.IP_CONTROL_RUN_swigconstant(_pypudding_w)
IP_CONTROL_RUN = _pypudding_w.IP_CONTROL_RUN

_pypudding_w.IP_CONTROL_RUN_CB_swigconstant(_pypudding_w)
IP_CONTROL_RUN_CB = _pypudding_w.IP_CONTROL_RUN_CB

_pypudding_w.IP_FDR_REGISTRATION_swigconstant(_pypudding_w)
IP_FDR_REGISTRATION = _pypudding_w.IP_FDR_REGISTRATION

_pypudding_w.IP_SEND_BLOBS_ON_FAIL_ONLY_swigconstant(_pypudding_w)
IP_SEND_BLOBS_ON_FAIL_ONLY = _pypudding_w.IP_SEND_BLOBS_ON_FAIL_ONLY

_pypudding_w.IP_SEND_BLOBS_ON_swigconstant(_pypudding_w)
IP_SEND_BLOBS_ON = _pypudding_w.IP_SEND_BLOBS_ON

_pypudding_w.IP_LIVE_VERSION_swigconstant(_pypudding_w)
IP_LIVE_VERSION = _pypudding_w.IP_LIVE_VERSION

_pypudding_w.IP_LIVE_CURRENT_swigconstant(_pypudding_w)
IP_LIVE_CURRENT = _pypudding_w.IP_LIVE_CURRENT

_pypudding_w.IP_LIVE_SCHEDULED_swigconstant(_pypudding_w)
IP_LIVE_SCHEDULED = _pypudding_w.IP_LIVE_SCHEDULED

_pypudding_w.IP_LIVE_VERSION_PATH_swigconstant(_pypudding_w)
IP_LIVE_VERSION_PATH = _pypudding_w.IP_LIVE_VERSION_PATH

_pypudding_w.IP_LINE_TYPE_swigconstant(_pypudding_w)
IP_LINE_TYPE = _pypudding_w.IP_LINE_TYPE

_pypudding_w.IP_GHSTATIONINFO_COUNT_swigconstant(_pypudding_w)
IP_GHSTATIONINFO_COUNT = _pypudding_w.IP_GHSTATIONINFO_COUNT

_pypudding_w.IP_MARINA_URL_swigconstant(_pypudding_w)
IP_MARINA_URL = _pypudding_w.IP_MARINA_URL

_pypudding_w.IP_MAX_NUMBER_BLOBS_swigconstant(_pypudding_w)
IP_MAX_NUMBER_BLOBS = _pypudding_w.IP_MAX_NUMBER_BLOBS

_pypudding_w.IP_FOREVER_swigconstant(_pypudding_w)
IP_FOREVER = _pypudding_w.IP_FOREVER

_pypudding_w.IP_30DAYS_swigconstant(_pypudding_w)
IP_30DAYS = _pypudding_w.IP_30DAYS

_pypudding_w.IP_60DAYS_swigconstant(_pypudding_w)
IP_60DAYS = _pypudding_w.IP_60DAYS

_pypudding_w.IP_90DAYS_swigconstant(_pypudding_w)
IP_90DAYS = _pypudding_w.IP_90DAYS

_pypudding_w.IP_180DAYS_swigconstant(_pypudding_w)
IP_180DAYS = _pypudding_w.IP_180DAYS

_pypudding_w.IP_270DAYS_swigconstant(_pypudding_w)
IP_270DAYS = _pypudding_w.IP_270DAYS

_pypudding_w.IP_360DAYS_swigconstant(_pypudding_w)
IP_360DAYS = _pypudding_w.IP_360DAYS

_pypudding_w.IP_FIXTURE_ID_1_swigconstant(_pypudding_w)
IP_FIXTURE_ID_1 = _pypudding_w.IP_FIXTURE_ID_1

_pypudding_w.IP_FIXTURE_ID_2_swigconstant(_pypudding_w)
IP_FIXTURE_ID_2 = _pypudding_w.IP_FIXTURE_ID_2

_pypudding_w.IP_FIXTURE_ID_3_swigconstant(_pypudding_w)
IP_FIXTURE_ID_3 = _pypudding_w.IP_FIXTURE_ID_3

_pypudding_w.IP_FIXTURE_ID_4_swigconstant(_pypudding_w)
IP_FIXTURE_ID_4 = _pypudding_w.IP_FIXTURE_ID_4

_pypudding_w.IP_FIXTURE_ID_5_swigconstant(_pypudding_w)
IP_FIXTURE_ID_5 = _pypudding_w.IP_FIXTURE_ID_5

_pypudding_w.IP_FIXTURE_ID_6_swigconstant(_pypudding_w)
IP_FIXTURE_ID_6 = _pypudding_w.IP_FIXTURE_ID_6

_pypudding_w.IP_FIXTURE_ID_7_swigconstant(_pypudding_w)
IP_FIXTURE_ID_7 = _pypudding_w.IP_FIXTURE_ID_7

_pypudding_w.IP_FIXTURE_ID_8_swigconstant(_pypudding_w)
IP_FIXTURE_ID_8 = _pypudding_w.IP_FIXTURE_ID_8

_pypudding_w.IP_FIXTURE_ID_9_swigconstant(_pypudding_w)
IP_FIXTURE_ID_9 = _pypudding_w.IP_FIXTURE_ID_9

_pypudding_w.IP_FIXTURE_ID_10_swigconstant(_pypudding_w)
IP_FIXTURE_ID_10 = _pypudding_w.IP_FIXTURE_ID_10

_pypudding_w.IP_FIXTURE_HEAD_ID_1_swigconstant(_pypudding_w)
IP_FIXTURE_HEAD_ID_1 = _pypudding_w.IP_FIXTURE_HEAD_ID_1

_pypudding_w.IP_FIXTURE_HEAD_ID_2_swigconstant(_pypudding_w)
IP_FIXTURE_HEAD_ID_2 = _pypudding_w.IP_FIXTURE_HEAD_ID_2

_pypudding_w.IP_FIXTURE_HEAD_ID_3_swigconstant(_pypudding_w)
IP_FIXTURE_HEAD_ID_3 = _pypudding_w.IP_FIXTURE_HEAD_ID_3

_pypudding_w.IP_FIXTURE_HEAD_ID_4_swigconstant(_pypudding_w)
IP_FIXTURE_HEAD_ID_4 = _pypudding_w.IP_FIXTURE_HEAD_ID_4

_pypudding_w.IP_FIXTURE_HEAD_ID_5_swigconstant(_pypudding_w)
IP_FIXTURE_HEAD_ID_5 = _pypudding_w.IP_FIXTURE_HEAD_ID_5

_pypudding_w.IP_FIXTURE_HEAD_ID_6_swigconstant(_pypudding_w)
IP_FIXTURE_HEAD_ID_6 = _pypudding_w.IP_FIXTURE_HEAD_ID_6

_pypudding_w.IP_ATTRIBUTE_SERIALNUMBER_swigconstant(_pypudding_w)
IP_ATTRIBUTE_SERIALNUMBER = _pypudding_w.IP_ATTRIBUTE_SERIALNUMBER

_pypudding_w.IP_ATTRIBUTE_STATIONSOFTWAREVERSION_swigconstant(_pypudding_w)
IP_ATTRIBUTE_STATIONSOFTWAREVERSION = _pypudding_w.IP_ATTRIBUTE_STATIONSOFTWAREVERSION

_pypudding_w.IP_ATTRIBUTE_STATIONSOFTWARENAME_swigconstant(_pypudding_w)
IP_ATTRIBUTE_STATIONSOFTWARENAME = _pypudding_w.IP_ATTRIBUTE_STATIONSOFTWARENAME

_pypudding_w.IP_ATTRIBUTE_STATIONLIMITSVERSION_swigconstant(_pypudding_w)
IP_ATTRIBUTE_STATIONLIMITSVERSION = _pypudding_w.IP_ATTRIBUTE_STATIONLIMITSVERSION

_pypudding_w.IP_ATTRIBUTE_OPERATOR_ID_swigconstant(_pypudding_w)
IP_ATTRIBUTE_OPERATOR_ID = _pypudding_w.IP_ATTRIBUTE_OPERATOR_ID

_pypudding_w.IP_ATTRIBUTE_HEAD_ID_swigconstant(_pypudding_w)
IP_ATTRIBUTE_HEAD_ID = _pypudding_w.IP_ATTRIBUTE_HEAD_ID

_pypudding_w.IP_ATTRIBUTE_FIXTURE_ID_swigconstant(_pypudding_w)
IP_ATTRIBUTE_FIXTURE_ID = _pypudding_w.IP_ATTRIBUTE_FIXTURE_ID

_pypudding_w.IP_ATTRIBUTE_SWVERSION_swigconstant(_pypudding_w)
IP_ATTRIBUTE_SWVERSION = _pypudding_w.IP_ATTRIBUTE_SWVERSION

_pypudding_w.IP_ATTRIBUTE_STATIONIDENTIFIER_swigconstant(_pypudding_w)
IP_ATTRIBUTE_STATIONIDENTIFIER = _pypudding_w.IP_ATTRIBUTE_STATIONIDENTIFIER

_pypudding_w.IP_ATTRIBUTE_STATIONSUBIDENTIFIER_swigconstant(_pypudding_w)
IP_ATTRIBUTE_STATIONSUBIDENTIFIER = _pypudding_w.IP_ATTRIBUTE_STATIONSUBIDENTIFIER

_pypudding_w.IP_ATTRIBUTE_BUILD_EVENT_swigconstant(_pypudding_w)
IP_ATTRIBUTE_BUILD_EVENT = _pypudding_w.IP_ATTRIBUTE_BUILD_EVENT

_pypudding_w.IP_ATTRIBUTE_BUILD_MATRIX_CONFIG_swigconstant(_pypudding_w)
IP_ATTRIBUTE_BUILD_MATRIX_CONFIG = _pypudding_w.IP_ATTRIBUTE_BUILD_MATRIX_CONFIG

_pypudding_w.IP_ATTRIBUTE_UNIT_NUMBER_swigconstant(_pypudding_w)
IP_ATTRIBUTE_UNIT_NUMBER = _pypudding_w.IP_ATTRIBUTE_UNIT_NUMBER

_pypudding_w.IP_ATTRIBUTE_SPECIAL_BUILD_swigconstant(_pypudding_w)
IP_ATTRIBUTE_SPECIAL_BUILD = _pypudding_w.IP_ATTRIBUTE_SPECIAL_BUILD

_pypudding_w.IP_ATTRIBUTE_MLBSERIALNUMBER_swigconstant(_pypudding_w)
IP_ATTRIBUTE_MLBSERIALNUMBER = _pypudding_w.IP_ATTRIBUTE_MLBSERIALNUMBER

_pypudding_w.IP_ATTRIBUTE_MACADDRESS_WIFI_swigconstant(_pypudding_w)
IP_ATTRIBUTE_MACADDRESS_WIFI = _pypudding_w.IP_ATTRIBUTE_MACADDRESS_WIFI

_pypudding_w.IP_ATTRIBUTE_MACADDRESS_BT_swigconstant(_pypudding_w)
IP_ATTRIBUTE_MACADDRESS_BT = _pypudding_w.IP_ATTRIBUTE_MACADDRESS_BT

_pypudding_w.IP_ATTRIBUTE_MACADDRESS_ENET_swigconstant(_pypudding_w)
IP_ATTRIBUTE_MACADDRESS_ENET = _pypudding_w.IP_ATTRIBUTE_MACADDRESS_ENET

_pypudding_w.IP_ATTRIBUTE_BATTERY_SERIAL_NUMBER_swigconstant(_pypudding_w)
IP_ATTRIBUTE_BATTERY_SERIAL_NUMBER = _pypudding_w.IP_ATTRIBUTE_BATTERY_SERIAL_NUMBER

_pypudding_w.IP_ATTRIBUTE_REGION_CODE_swigconstant(_pypudding_w)
IP_ATTRIBUTE_REGION_CODE = _pypudding_w.IP_ATTRIBUTE_REGION_CODE

_pypudding_w.IP_ATTRIBUTE_MPN_swigconstant(_pypudding_w)
IP_ATTRIBUTE_MPN = _pypudding_w.IP_ATTRIBUTE_MPN

_pypudding_w.IP_ATTRIBUTE_IMEI_swigconstant(_pypudding_w)
IP_ATTRIBUTE_IMEI = _pypudding_w.IP_ATTRIBUTE_IMEI

_pypudding_w.IP_ATTRIBUTE_BASEBAND_VERSION_swigconstant(_pypudding_w)
IP_ATTRIBUTE_BASEBAND_VERSION = _pypudding_w.IP_ATTRIBUTE_BASEBAND_VERSION

_pypudding_w.IP_ATTRIBUTE_BOOTCORE_VERSION_swigconstant(_pypudding_w)
IP_ATTRIBUTE_BOOTCORE_VERSION = _pypudding_w.IP_ATTRIBUTE_BOOTCORE_VERSION

_pypudding_w.IP_ATTRIBUTE_OS_BUILD_VERSION_swigconstant(_pypudding_w)
IP_ATTRIBUTE_OS_BUILD_VERSION = _pypudding_w.IP_ATTRIBUTE_OS_BUILD_VERSION

_pypudding_w.IP_ATTRIBUTE_CAMERA_CONFIG_swigconstant(_pypudding_w)
IP_ATTRIBUTE_CAMERA_CONFIG = _pypudding_w.IP_ATTRIBUTE_CAMERA_CONFIG

_pypudding_w.IP_ATTRIBUTE_ECID_swigconstant(_pypudding_w)
IP_ATTRIBUTE_ECID = _pypudding_w.IP_ATTRIBUTE_ECID

_pypudding_w.IP_ATTRIBUTE_DIAG_DATE_swigconstant(_pypudding_w)
IP_ATTRIBUTE_DIAG_DATE = _pypudding_w.IP_ATTRIBUTE_DIAG_DATE

_pypudding_w.IP_ATTRIBUTE_DIAG_VERSION_swigconstant(_pypudding_w)
IP_ATTRIBUTE_DIAG_VERSION = _pypudding_w.IP_ATTRIBUTE_DIAG_VERSION

_pypudding_w.IP_ATTRIBUTE_CHIP_SN_swigconstant(_pypudding_w)
IP_ATTRIBUTE_CHIP_SN = _pypudding_w.IP_ATTRIBUTE_CHIP_SN

_pypudding_w.IP_ATTRIBUTE_BASEBAND_SN_swigconstant(_pypudding_w)
IP_ATTRIBUTE_BASEBAND_SN = _pypudding_w.IP_ATTRIBUTE_BASEBAND_SN

_pypudding_w.IP_ATTRIBUTE_PRODUCTION_SOC_swigconstant(_pypudding_w)
IP_ATTRIBUTE_PRODUCTION_SOC = _pypudding_w.IP_ATTRIBUTE_PRODUCTION_SOC

_pypudding_w.IP_ATTRIBUTE_UDID_swigconstant(_pypudding_w)
IP_ATTRIBUTE_UDID = _pypudding_w.IP_ATTRIBUTE_UDID

_pypudding_w.IP_FAIL_ABOVE_SPEC_swigconstant(_pypudding_w)
IP_FAIL_ABOVE_SPEC = _pypudding_w.IP_FAIL_ABOVE_SPEC

_pypudding_w.IP_FAIL_BELOW_SPEC_swigconstant(_pypudding_w)
IP_FAIL_BELOW_SPEC = _pypudding_w.IP_FAIL_BELOW_SPEC

_pypudding_w.IP_FAIL_COMMUNICATION_UUT_swigconstant(_pypudding_w)
IP_FAIL_COMMUNICATION_UUT = _pypudding_w.IP_FAIL_COMMUNICATION_UUT

_pypudding_w.IP_FAIL_COMMUNICATION_EQUIPMENT_swigconstant(_pypudding_w)
IP_FAIL_COMMUNICATION_EQUIPMENT = _pypudding_w.IP_FAIL_COMMUNICATION_EQUIPMENT

_pypudding_w.IP_FAIL_WRITING_NOR_swigconstant(_pypudding_w)
IP_FAIL_WRITING_NOR = _pypudding_w.IP_FAIL_WRITING_NOR

_pypudding_w.IP_FAIL_READING_NOR_swigconstant(_pypudding_w)
IP_FAIL_READING_NOR = _pypudding_w.IP_FAIL_READING_NOR

_pypudding_w.IP_FAIL_CONTROL_BIT_NOT_SET_swigconstant(_pypudding_w)
IP_FAIL_CONTROL_BIT_NOT_SET = _pypudding_w.IP_FAIL_CONTROL_BIT_NOT_SET

_pypudding_w.IP_FAIL_INVALID_SERIAL_NUMBER_swigconstant(_pypudding_w)
IP_FAIL_INVALID_SERIAL_NUMBER = _pypudding_w.IP_FAIL_INVALID_SERIAL_NUMBER

_pypudding_w.IP_FAIL_INVALID_STATION_ID_swigconstant(_pypudding_w)
IP_FAIL_INVALID_STATION_ID = _pypudding_w.IP_FAIL_INVALID_STATION_ID

_pypudding_w.IP_FAIL_NO_AUDIO_swigconstant(_pypudding_w)
IP_FAIL_NO_AUDIO = _pypudding_w.IP_FAIL_NO_AUDIO

_pypudding_w.IP_UNITS_DB_swigconstant(_pypudding_w)
IP_UNITS_DB = _pypudding_w.IP_UNITS_DB

_pypudding_w.IP_UNITS_DBV_swigconstant(_pypudding_w)
IP_UNITS_DBV = _pypudding_w.IP_UNITS_DBV

_pypudding_w.IP_UNITS_DBM_swigconstant(_pypudding_w)
IP_UNITS_DBM = _pypudding_w.IP_UNITS_DBM

_pypudding_w.IP_UNITS_DBR_swigconstant(_pypudding_w)
IP_UNITS_DBR = _pypudding_w.IP_UNITS_DBR

_pypudding_w.IP_UNITS_DBW_swigconstant(_pypudding_w)
IP_UNITS_DBW = _pypudding_w.IP_UNITS_DBW

_pypudding_w.IP_UNITS_DBVPASCAL_swigconstant(_pypudding_w)
IP_UNITS_DBVPASCAL = _pypudding_w.IP_UNITS_DBVPASCAL

_pypudding_w.IP_UNITS_DBPASCALV_swigconstant(_pypudding_w)
IP_UNITS_DBPASCALV = _pypudding_w.IP_UNITS_DBPASCALV

_pypudding_w.IP_UNITS_VOLTS_swigconstant(_pypudding_w)
IP_UNITS_VOLTS = _pypudding_w.IP_UNITS_VOLTS

_pypudding_w.IP_UNITS_MILLIVOLTS_swigconstant(_pypudding_w)
IP_UNITS_MILLIVOLTS = _pypudding_w.IP_UNITS_MILLIVOLTS

_pypudding_w.IP_UNITS_WATTS_swigconstant(_pypudding_w)
IP_UNITS_WATTS = _pypudding_w.IP_UNITS_WATTS

_pypudding_w.IP_UNITS_MILLIWATTS_swigconstant(_pypudding_w)
IP_UNITS_MILLIWATTS = _pypudding_w.IP_UNITS_MILLIWATTS

_pypudding_w.IP_UNITS_AMPERES_swigconstant(_pypudding_w)
IP_UNITS_AMPERES = _pypudding_w.IP_UNITS_AMPERES

_pypudding_w.IP_UNITS_MILLIAMPERES_swigconstant(_pypudding_w)
IP_UNITS_MILLIAMPERES = _pypudding_w.IP_UNITS_MILLIAMPERES

_pypudding_w.IP_UNITS_OHMS_swigconstant(_pypudding_w)
IP_UNITS_OHMS = _pypudding_w.IP_UNITS_OHMS

_pypudding_w.IP_UNTIS_MILLIOHMS_swigconstant(_pypudding_w)
IP_UNTIS_MILLIOHMS = _pypudding_w.IP_UNTIS_MILLIOHMS

_pypudding_w.IP_UNTIS_KILOOHMS_swigconstant(_pypudding_w)
IP_UNTIS_KILOOHMS = _pypudding_w.IP_UNTIS_KILOOHMS

_pypudding_w.IP_UNITS_MEGAOHMS_swigconstant(_pypudding_w)
IP_UNITS_MEGAOHMS = _pypudding_w.IP_UNITS_MEGAOHMS

_pypudding_w.IP_UNITS_RMS_swigconstant(_pypudding_w)
IP_UNITS_RMS = _pypudding_w.IP_UNITS_RMS

_pypudding_w.IP_UNITS_HZ_swigconstant(_pypudding_w)
IP_UNITS_HZ = _pypudding_w.IP_UNITS_HZ

_pypudding_w.IP_UNITS_KHZ_swigconstant(_pypudding_w)
IP_UNITS_KHZ = _pypudding_w.IP_UNITS_KHZ

_pypudding_w.IP_UNITS_MHZ_swigconstant(_pypudding_w)
IP_UNITS_MHZ = _pypudding_w.IP_UNITS_MHZ

_pypudding_w.IP_UNITS_FOOTLBS_swigconstant(_pypudding_w)
IP_UNITS_FOOTLBS = _pypudding_w.IP_UNITS_FOOTLBS

_pypudding_w.IP_UNITS_PERCENT_swigconstant(_pypudding_w)
IP_UNITS_PERCENT = _pypudding_w.IP_UNITS_PERCENT

_pypudding_w.IP_UNITS_MM_swigconstant(_pypudding_w)
IP_UNITS_MM = _pypudding_w.IP_UNITS_MM

_pypudding_w.IP_UNITS_INCHES_swigconstant(_pypudding_w)
IP_UNITS_INCHES = _pypudding_w.IP_UNITS_INCHES

_pypudding_w.IP_UNITS_MILES_swigconstant(_pypudding_w)
IP_UNITS_MILES = _pypudding_w.IP_UNITS_MILES

_pypudding_w.IP_UNITS_PARSECS_swigconstant(_pypudding_w)
IP_UNITS_PARSECS = _pypudding_w.IP_UNITS_PARSECS

_pypudding_w.IP_NOVALUE_swigconstant(_pypudding_w)
IP_NOVALUE = _pypudding_w.IP_NOVALUE

_pypudding_w.IP_RETVALUE_swigconstant(_pypudding_w)
IP_RETVALUE = _pypudding_w.IP_RETVALUE

_pypudding_w.IP_PRIORITY_STATION_CALIBRATION_AUDIT_swigconstant(_pypudding_w)
IP_PRIORITY_STATION_CALIBRATION_AUDIT = _pypudding_w.IP_PRIORITY_STATION_CALIBRATION_AUDIT

_pypudding_w.IP_PRIORITY_STATION_GRR_swigconstant(_pypudding_w)
IP_PRIORITY_STATION_GRR = _pypudding_w.IP_PRIORITY_STATION_GRR

_pypudding_w.IP_PRIORITY_REALTIME_WITH_ALARMS_swigconstant(_pypudding_w)
IP_PRIORITY_REALTIME_WITH_ALARMS = _pypudding_w.IP_PRIORITY_REALTIME_WITH_ALARMS

_pypudding_w.IP_PRIORITY_REALTIME_swigconstant(_pypudding_w)
IP_PRIORITY_REALTIME = _pypudding_w.IP_PRIORITY_REALTIME

_pypudding_w.IP_PRIORITY_DELAYED_WITH_DAILY_ALARMS_swigconstant(_pypudding_w)
IP_PRIORITY_DELAYED_WITH_DAILY_ALARMS = _pypudding_w.IP_PRIORITY_DELAYED_WITH_DAILY_ALARMS

_pypudding_w.IP_PRIORITY_DELAYED_IMPORT_swigconstant(_pypudding_w)
IP_PRIORITY_DELAYED_IMPORT = _pypudding_w.IP_PRIORITY_DELAYED_IMPORT

_pypudding_w.IP_PRIORITY_ARCHIVE_swigconstant(_pypudding_w)
IP_PRIORITY_ARCHIVE = _pypudding_w.IP_PRIORITY_ARCHIVE

_pypudding_w.IP_MSG_RESULT_OFFSET_swigconstant(_pypudding_w)
IP_MSG_RESULT_OFFSET = _pypudding_w.IP_MSG_RESULT_OFFSET

_pypudding_w.IP_MSG_RESULT_PASS_swigconstant(_pypudding_w)
IP_MSG_RESULT_PASS = _pypudding_w.IP_MSG_RESULT_PASS

_pypudding_w.IP_MSG_RESULT_FAIL_swigconstant(_pypudding_w)
IP_MSG_RESULT_FAIL = _pypudding_w.IP_MSG_RESULT_FAIL

_pypudding_w.IP_MSG_CLASS_OFFSET_swigconstant(_pypudding_w)
IP_MSG_CLASS_OFFSET = _pypudding_w.IP_MSG_CLASS_OFFSET

_pypudding_w.IP_MSG_CLASS_UNCLASSIFIED_swigconstant(_pypudding_w)
IP_MSG_CLASS_UNCLASSIFIED = _pypudding_w.IP_MSG_CLASS_UNCLASSIFIED

_pypudding_w.IP_MSG_CLASS_API_ERROR_swigconstant(_pypudding_w)
IP_MSG_CLASS_API_ERROR = _pypudding_w.IP_MSG_CLASS_API_ERROR

_pypudding_w.IP_MSG_CLASS_COMM_ERR_swigconstant(_pypudding_w)
IP_MSG_CLASS_COMM_ERR = _pypudding_w.IP_MSG_CLASS_COMM_ERR

_pypudding_w.IP_MSG_CLASS_QUERY_swigconstant(_pypudding_w)
IP_MSG_CLASS_QUERY = _pypudding_w.IP_MSG_CLASS_QUERY

_pypudding_w.IP_MSG_CLASS_QUERY_RESPONSE_swigconstant(_pypudding_w)
IP_MSG_CLASS_QUERY_RESPONSE = _pypudding_w.IP_MSG_CLASS_QUERY_RESPONSE

_pypudding_w.IP_MSG_CLASS_QUERY_DELAYED_RESPONSE_swigconstant(_pypudding_w)
IP_MSG_CLASS_QUERY_DELAYED_RESPONSE = _pypudding_w.IP_MSG_CLASS_QUERY_DELAYED_RESPONSE

_pypudding_w.IP_MSG_CLASS_PROCESS_CONTROL_swigconstant(_pypudding_w)
IP_MSG_CLASS_PROCESS_CONTROL = _pypudding_w.IP_MSG_CLASS_PROCESS_CONTROL

_pypudding_w.IP_MSG_CLASS_COUNT_swigconstant(_pypudding_w)
IP_MSG_CLASS_COUNT = _pypudding_w.IP_MSG_CLASS_COUNT

_pypudding_w.IP_MSG_RESERVED_OFFSET_swigconstant(_pypudding_w)
IP_MSG_RESERVED_OFFSET = _pypudding_w.IP_MSG_RESERVED_OFFSET

_pypudding_w.IP_MSG_IDENTIFIER_OFFSET_swigconstant(_pypudding_w)
IP_MSG_IDENTIFIER_OFFSET = _pypudding_w.IP_MSG_IDENTIFIER_OFFSET

_pypudding_w.IP_QUERY_AMIOK_swigconstant(_pypudding_w)
IP_QUERY_AMIOK = _pypudding_w.IP_QUERY_AMIOK

_pypudding_w.IP_QUERY_STATION_SW_swigconstant(_pypudding_w)
IP_QUERY_STATION_SW = _pypudding_w.IP_QUERY_STATION_SW

_pypudding_w.IP_QUERY_COUNT_swigconstant(_pypudding_w)
IP_QUERY_COUNT = _pypudding_w.IP_QUERY_COUNT

_pypudding_w.IP_MSG_ERROR_API_UNHANDLED_swigconstant(_pypudding_w)
IP_MSG_ERROR_API_UNHANDLED = _pypudding_w.IP_MSG_ERROR_API_UNHANDLED

_pypudding_w.IP_MSG_ERROR_UNIT_ID_INVALID_swigconstant(_pypudding_w)
IP_MSG_ERROR_UNIT_ID_INVALID = _pypudding_w.IP_MSG_ERROR_UNIT_ID_INVALID

_pypudding_w.IP_MSG_ERROR_UNIMPLEMENTED_swigconstant(_pypudding_w)
IP_MSG_ERROR_UNIMPLEMENTED = _pypudding_w.IP_MSG_ERROR_UNIMPLEMENTED

_pypudding_w.IP_MSG_ERROR_API_VERSION_swigconstant(_pypudding_w)
IP_MSG_ERROR_API_VERSION = _pypudding_w.IP_MSG_ERROR_API_VERSION

_pypudding_w.IP_MSG_ERROR_API_SYNTAX_swigconstant(_pypudding_w)
IP_MSG_ERROR_API_SYNTAX = _pypudding_w.IP_MSG_ERROR_API_SYNTAX

_pypudding_w.IP_MSG_ERROR_API_NO_ATTRIBUTE_swigconstant(_pypudding_w)
IP_MSG_ERROR_API_NO_ATTRIBUTE = _pypudding_w.IP_MSG_ERROR_API_NO_ATTRIBUTE

_pypudding_w.IP_MSG_ERROR_FERRET_NOT_RUNNING_swigconstant(_pypudding_w)
IP_MSG_ERROR_FERRET_NOT_RUNNING = _pypudding_w.IP_MSG_ERROR_FERRET_NOT_RUNNING

_pypudding_w.IP_MSG_ERROR_FILESYSTEM_swigconstant(_pypudding_w)
IP_MSG_ERROR_FILESYSTEM = _pypudding_w.IP_MSG_ERROR_FILESYSTEM

_pypudding_w.IP_MSG_ERROR_NETWORK_swigconstant(_pypudding_w)
IP_MSG_ERROR_NETWORK = _pypudding_w.IP_MSG_ERROR_NETWORK

_pypudding_w.IP_MSG_ERROR_INVALID_SERIAL_NUMBER_swigconstant(_pypudding_w)
IP_MSG_ERROR_INVALID_SERIAL_NUMBER = _pypudding_w.IP_MSG_ERROR_INVALID_SERIAL_NUMBER

_pypudding_w.IP_MSG_ERROR_DCS_NOT_RESPONDING_swigconstant(_pypudding_w)
IP_MSG_ERROR_DCS_NOT_RESPONDING = _pypudding_w.IP_MSG_ERROR_DCS_NOT_RESPONDING

_pypudding_w.IP_MSG_ERROR_PDCA_NOT_RESPONDING_swigconstant(_pypudding_w)
IP_MSG_ERROR_PDCA_NOT_RESPONDING = _pypudding_w.IP_MSG_ERROR_PDCA_NOT_RESPONDING

_pypudding_w.IP_MSG_ERROR_GROUNDHOG_NOT_RESPONDING_swigconstant(_pypudding_w)
IP_MSG_ERROR_GROUNDHOG_NOT_RESPONDING = _pypudding_w.IP_MSG_ERROR_GROUNDHOG_NOT_RESPONDING

_pypudding_w.IP_MSG_ERROR_NETWORK_NOT_RESPONDING_swigconstant(_pypudding_w)
IP_MSG_ERROR_NETWORK_NOT_RESPONDING = _pypudding_w.IP_MSG_ERROR_NETWORK_NOT_RESPONDING

_pypudding_w.IP_MSG_ERROR_ETHERNET_NOT_RESPONDING_swigconstant(_pypudding_w)
IP_MSG_ERROR_ETHERNET_NOT_RESPONDING = _pypudding_w.IP_MSG_ERROR_ETHERNET_NOT_RESPONDING

_pypudding_w.IP_MSG_ERROR_UNIT_OUT_OF_PROCESS_swigconstant(_pypudding_w)
IP_MSG_ERROR_UNIT_OUT_OF_PROCESS = _pypudding_w.IP_MSG_ERROR_UNIT_OUT_OF_PROCESS

_pypudding_w.IP_MSG_ERROR_INVALID_STATION_TYPE_swigconstant(_pypudding_w)
IP_MSG_ERROR_INVALID_STATION_TYPE = _pypudding_w.IP_MSG_ERROR_INVALID_STATION_TYPE

_pypudding_w.IP_MSG_ERROR_INVALID_SW_VERSION_swigconstant(_pypudding_w)
IP_MSG_ERROR_INVALID_SW_VERSION = _pypudding_w.IP_MSG_ERROR_INVALID_SW_VERSION

_pypudding_w.IP_MSG_ERROR_INVALID_IP_VERSION_swigconstant(_pypudding_w)
IP_MSG_ERROR_INVALID_IP_VERSION = _pypudding_w.IP_MSG_ERROR_INVALID_IP_VERSION

_pypudding_w.IP_MSG_ERROR_INVALID_FERRET_VERSION_swigconstant(_pypudding_w)
IP_MSG_ERROR_INVALID_FERRET_VERSION = _pypudding_w.IP_MSG_ERROR_INVALID_FERRET_VERSION

_pypudding_w.IP_MSG_ERROR_INVALID_GHSTATIONINFO_VALUE_swigconstant(_pypudding_w)
IP_MSG_ERROR_INVALID_GHSTATIONINFO_VALUE = _pypudding_w.IP_MSG_ERROR_INVALID_GHSTATIONINFO_VALUE

_pypudding_w.IP_MSG_ERROR_INVALID_DATA_FORMAT_swigconstant(_pypudding_w)
IP_MSG_ERROR_INVALID_DATA_FORMAT = _pypudding_w.IP_MSG_ERROR_INVALID_DATA_FORMAT

_pypudding_w.IP_MSG_UNIT_GOLDEN_UNIT_swigconstant(_pypudding_w)
IP_MSG_UNIT_GOLDEN_UNIT = _pypudding_w.IP_MSG_UNIT_GOLDEN_UNIT

_pypudding_w.IP_MSG_UNIT_OUTLIER_swigconstant(_pypudding_w)
IP_MSG_UNIT_OUTLIER = _pypudding_w.IP_MSG_UNIT_OUTLIER

_pypudding_w.IP_MSG_UNIT_ESCAPE_swigconstant(_pypudding_w)
IP_MSG_UNIT_ESCAPE = _pypudding_w.IP_MSG_UNIT_ESCAPE

_pypudding_w.IP_MSG_UNIT_FORCE_FAIL_swigconstant(_pypudding_w)
IP_MSG_UNIT_FORCE_FAIL = _pypudding_w.IP_MSG_UNIT_FORCE_FAIL

_pypudding_w.IP_MSG_UNIT_RECALL_swigconstant(_pypudding_w)
IP_MSG_UNIT_RECALL = _pypudding_w.IP_MSG_UNIT_RECALL

_pypudding_w.IP_MSG_UNIT_HOLD_swigconstant(_pypudding_w)
IP_MSG_UNIT_HOLD = _pypudding_w.IP_MSG_UNIT_HOLD

_pypudding_w.IP_MSG_UNIT_NOT_IN_SFC_swigconstant(_pypudding_w)
IP_MSG_UNIT_NOT_IN_SFC = _pypudding_w.IP_MSG_UNIT_NOT_IN_SFC

_pypudding_w.IP_MSG_STATION_SW_MISMATCH_swigconstant(_pypudding_w)
IP_MSG_STATION_SW_MISMATCH = _pypudding_w.IP_MSG_STATION_SW_MISMATCH

_pypudding_w.IP_MSG_STATION_OUTLIER_swigconstant(_pypudding_w)
IP_MSG_STATION_OUTLIER = _pypudding_w.IP_MSG_STATION_OUTLIER

_pypudding_w.IP_MSG_ERROR_INVALID_SIGNATURE_swigconstant(_pypudding_w)
IP_MSG_ERROR_INVALID_SIGNATURE = _pypudding_w.IP_MSG_ERROR_INVALID_SIGNATURE

_pypudding_w.IP_MSG_ERROR_INVALID_ATTRIBUTE_swigconstant(_pypudding_w)
IP_MSG_ERROR_INVALID_ATTRIBUTE = _pypudding_w.IP_MSG_ERROR_INVALID_ATTRIBUTE

_pypudding_w.IP_MSG_ERROR_SFC_QUERY_UNIT_swigconstant(_pypudding_w)
IP_MSG_ERROR_SFC_QUERY_UNIT = _pypudding_w.IP_MSG_ERROR_SFC_QUERY_UNIT

_pypudding_w.IP_MSG_ERROR_UMBRELLA_AMIOKAY_swigconstant(_pypudding_w)
IP_MSG_ERROR_UMBRELLA_AMIOKAY = _pypudding_w.IP_MSG_ERROR_UMBRELLA_AMIOKAY

_pypudding_w.IP_MSG_ERROR_INVALID_STATION_ID_swigconstant(_pypudding_w)
IP_MSG_ERROR_INVALID_STATION_ID = _pypudding_w.IP_MSG_ERROR_INVALID_STATION_ID

_pypudding_w.IP_MSG_ERROR_TIMESERVER_NOT_RESPONDING_swigconstant(_pypudding_w)
IP_MSG_ERROR_TIMESERVER_NOT_RESPONDING = _pypudding_w.IP_MSG_ERROR_TIMESERVER_NOT_RESPONDING

_pypudding_w.IP_MSG_USER_swigconstant(_pypudding_w)
IP_MSG_USER = _pypudding_w.IP_MSG_USER

_pypudding_w.IP_MSG_COUNT_swigconstant(_pypudding_w)
IP_MSG_COUNT = _pypudding_w.IP_MSG_COUNT

def IP_getVersion():
    return _pypudding_w.IP_getVersion()
IP_getVersion = _pypudding_w.IP_getVersion

def IP_UUTStart():
    return _pypudding_w.IP_UUTStart()
IP_UUTStart = _pypudding_w.IP_UUTStart

def IP_UUTCancel(inHandle):
    return _pypudding_w.IP_UUTCancel(inHandle)
IP_UUTCancel = _pypudding_w.IP_UUTCancel

def IP_UUTDone(inHandle):
    return _pypudding_w.IP_UUTDone(inHandle)
IP_UUTDone = _pypudding_w.IP_UUTDone

def IP_UUTCommit(inHandle, inPassFail):
    return _pypudding_w.IP_UUTCommit(inHandle, inPassFail)
IP_UUTCommit = _pypudding_w.IP_UUTCommit

def IP_UID_destroy(UUTHandle):
    return _pypudding_w.IP_UID_destroy(UUTHandle)
IP_UID_destroy = _pypudding_w.IP_UID_destroy

def IP_addResult(inHandle, testSpec, testResult):
    return _pypudding_w.IP_addResult(inHandle, testSpec, testResult)
IP_addResult = _pypudding_w.IP_addResult

def IP_addAttribute(inHandle, name, value):
    return _pypudding_w.IP_addAttribute(inHandle, name, value)
IP_addAttribute = _pypudding_w.IP_addAttribute

def IP_addBlob(inHandle, inBlobName, inPathToBlobFile):
    return _pypudding_w.IP_addBlob(inHandle, inBlobName, inPathToBlobFile)
IP_addBlob = _pypudding_w.IP_addBlob

def IP_addBlobWithPolicy(inHandle, eIPBlobPolicy, kcpBlobName, kcpPathToBlobFile):
    return _pypudding_w.IP_addBlobWithPolicy(inHandle, eIPBlobPolicy, kcpBlobName, kcpPathToBlobFile)
IP_addBlobWithPolicy = _pypudding_w.IP_addBlobWithPolicy

def IP_amIOkay(inHandle, inUUTSerialNumber):
    return _pypudding_w.IP_amIOkay(inHandle, inUUTSerialNumber)
IP_amIOkay = _pypudding_w.IP_amIOkay

def IP_reply_getError(reply):
    return _pypudding_w.IP_reply_getError(reply)
IP_reply_getError = _pypudding_w.IP_reply_getError

def IP_reply_getClass(replyToCheck):
    return _pypudding_w.IP_reply_getClass(replyToCheck)
IP_reply_getClass = _pypudding_w.IP_reply_getClass

def IP_reply_isOfClass(replyToCheck, classToCompare):
    return _pypudding_w.IP_reply_isOfClass(replyToCheck, classToCompare)
IP_reply_isOfClass = _pypudding_w.IP_reply_isOfClass

def IP_reply_getMessageID(replyToCheck):
    return _pypudding_w.IP_reply_getMessageID(replyToCheck)
IP_reply_getMessageID = _pypudding_w.IP_reply_getMessageID

def IP_reply_destroy(reply):
    return _pypudding_w.IP_reply_destroy(reply)
IP_reply_destroy = _pypudding_w.IP_reply_destroy

def IP_success(reply):
    return _pypudding_w.IP_success(reply)
IP_success = _pypudding_w.IP_success

def IP_testResult_create():
    return _pypudding_w.IP_testResult_create()
IP_testResult_create = _pypudding_w.IP_testResult_create

def IP_testResult_setResult(testResultHandle, result):
    return _pypudding_w.IP_testResult_setResult(testResultHandle, result)
IP_testResult_setResult = _pypudding_w.IP_testResult_setResult

def IP_testResult_setValue(testResultHandle, value):
    return _pypudding_w.IP_testResult_setValue(testResultHandle, value)
IP_testResult_setValue = _pypudding_w.IP_testResult_setValue

def IP_testResult_setMessage(testResultHandle, message):
    return _pypudding_w.IP_testResult_setMessage(testResultHandle, message)
IP_testResult_setMessage = _pypudding_w.IP_testResult_setMessage

def IP_testResult_destroy(testResultHandle):
    return _pypudding_w.IP_testResult_destroy(testResultHandle)
IP_testResult_destroy = _pypudding_w.IP_testResult_destroy

def IP_testSpec_create():
    return _pypudding_w.IP_testSpec_create()
IP_testSpec_create = _pypudding_w.IP_testSpec_create

def IP_testSpec_setTestName(testSpecHandle, name):
    return _pypudding_w.IP_testSpec_setTestName(testSpecHandle, name)
IP_testSpec_setTestName = _pypudding_w.IP_testSpec_setTestName

def IP_testSpec_setSubTestName(testSpecHandle, name):
    return _pypudding_w.IP_testSpec_setSubTestName(testSpecHandle, name)
IP_testSpec_setSubTestName = _pypudding_w.IP_testSpec_setSubTestName

def IP_testSpec_setSubSubTestName(testSpecHandle, name):
    return _pypudding_w.IP_testSpec_setSubSubTestName(testSpecHandle, name)
IP_testSpec_setSubSubTestName = _pypudding_w.IP_testSpec_setSubSubTestName

def IP_testSpec_setLimits(testSpecHandle, lowerLimit, upperLimit):
    return _pypudding_w.IP_testSpec_setLimits(testSpecHandle, lowerLimit, upperLimit)
IP_testSpec_setLimits = _pypudding_w.IP_testSpec_setLimits

def IP_testSpec_setUnits(testSpecHandle, units):
    return _pypudding_w.IP_testSpec_setUnits(testSpecHandle, units)
IP_testSpec_setUnits = _pypudding_w.IP_testSpec_setUnits

def IP_testSpec_setPriority(testSpecHandle, priority):
    return _pypudding_w.IP_testSpec_setPriority(testSpecHandle, priority)
IP_testSpec_setPriority = _pypudding_w.IP_testSpec_setPriority

def IP_testSpec_setTestContext(testSpecHandle, cpTestContxt, testContextLength):
    return _pypudding_w.IP_testSpec_setTestContext(testSpecHandle, cpTestContxt, testContextLength)
IP_testSpec_setTestContext = _pypudding_w.IP_testSpec_setTestContext

def IP_testSpec_setAsNonTestItem(testSpecHandle):
    return _pypudding_w.IP_testSpec_setAsNonTestItem(testSpecHandle)
IP_testSpec_setAsNonTestItem = _pypudding_w.IP_testSpec_setAsNonTestItem

def IP_testSpec_destroy(testSpecHandle):
    return _pypudding_w.IP_testSpec_destroy(testSpecHandle)
IP_testSpec_destroy = _pypudding_w.IP_testSpec_destroy

def IP_validateSerialNumber(inHandle, serialNumber):
    return _pypudding_w.IP_validateSerialNumber(inHandle, serialNumber)
IP_validateSerialNumber = _pypudding_w.IP_validateSerialNumber

def IP_getGHStationInfo(handleGHStation, eGHStationInfo):
    return _pypudding_w.IP_getGHStationInfo(handleGHStation, eGHStationInfo)
IP_getGHStationInfo = _pypudding_w.IP_getGHStationInfo

def IP_setDUTPosition(handleDUTPosition, eFixId, eHeadId):
    return _pypudding_w.IP_setDUTPosition(handleDUTPosition, eFixId, eHeadId)
IP_setDUTPosition = _pypudding_w.IP_setDUTPosition

def IP_setDUTPos(handleDUTPosition, cpFixId, cpHeadId):
    return _pypudding_w.IP_setDUTPos(handleDUTPosition, cpFixId, cpHeadId)
IP_setDUTPos = _pypudding_w.IP_setDUTPos

def IP_setStartTime(handleStartTime, rawTimeToUse):
    return _pypudding_w.IP_setStartTime(handleStartTime, rawTimeToUse)
IP_setStartTime = _pypudding_w.IP_setStartTime

def IP_setStopTime(handleStopTime, rawTimeToUse):
    return _pypudding_w.IP_setStopTime(handleStopTime, rawTimeToUse)
IP_setStopTime = _pypudding_w.IP_setStopTime
# This file is compatible with both classic and new-style classes.


