sudo: false
language: python
python: 2.7
services:
  - redis-server
env:
  - SCRAPY="scrapy==1.0.0"
  - SCRAPY="scrapy>=1.0.0"
install:
  - pip install $SCRAPY
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script: py.test
